services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /dev/null:/var/www/html/index.php
      - ./public-files:/var/www/html/files
      - ./assets:/var/www/html/./assets
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais
    networks:
      - mapaservices

  mapasculturais:
    image: secultceara/mapasculturais:homolog
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./assets:/var/www/html/./assets
      - ./public-files:/var/www/html/files
      - ./private-files:/var/www/./private-files
      - ./saas-files:/var/www/SaaS
      - ./sessions:/var/www/var/./sessions
      - ./logs:/var/www/var/./logs
    links:
      - redis
      - sessions

    depends_on:
      - redis
      - sessions
    networks:
      - mapaservices

  redis:
    image: redis:6
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - mapaservices

  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    # volumes:
    #   - ./sessions:/data
    networks:
      - mapaservices

networks:
  mapaservices:
    # external: true

# volumes:
#   ./assets:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./assets
#       o: bind

#   ./logs:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./logs
#       o: bind

#   ./private-files:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./private-files
#       o: bind

#   ./public-files:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./public-files
#       o: bind
  
#   ./saas-files:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./saas-files
#       o: bind
  
#   ./sessions:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mapacultural/./sessions
#       o: bind